#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$0")

cd "$SCRIPT_DIR"

RUN_ALL_TEST=
RUN_LIST=
NEOVIM_BIN_PATH=${JSJ_NEOVIM_BIN:-$(command -v nvim)}

if [[ "$TERM" == "dumb" ]]; then
  RED='\e[1;31m'
  RESET='\e[0m'
else
  RED=
  RESET=
fi

_have() { type "$1" &>/dev/null; }

fatal() {
  echo -e "${RED}FATAL_ERROR${RESET}: $*"
  exit 1
}

single_test() {
  local test_case=${1:-}
  [[ -z "$test_case" ]] && fatal "No test case specified"
  [[ -f "$test_case" ]] || fatal "test case ($test_case) not found"

  eval "$NEOVIM_BIN_PATH --clean --headless -c 'set rtp+=.' -l '$test_case'" || exit 1
}

all_test() {
  local case

  shopt -s nullglob

  for case in tests/cfg/*.lua tests/matchers/*.lua; do
    echo "--------------------------------------------------------------------"
    single_test "$case" || exit 1
    echo "--------------------------------------------------------------------"
  done

  exit 0
}

list() {
  local all_cases=$(find tests/cfg/ tests/matchers/ -type f -name '*.lua')
  local case

  if _have fzf; then
    printf "%s" "$all_cases" | fzf --multi |\
      while IFS= read -r case; do
        echo "--------------------------------------------------------------------"
        single_test "$case" || exit 1
        echo "--------------------------------------------------------------------"
      done
  else
    echo "$all_cases"
  fi

  exit 0
}

main() {
  while getopts "n:al" opt; do
    case "$opt" in
      a)
        RUN_ALL_TEST=1
        ;;
      n)
        NEOVIM_BIN_PATH="$OPTARG"
        ;;
      l)
        RUN_LIST=1
        ;;
    esac
  done
  shift $((OPTIND - 1))
  [[ -x "$NEOVIM_BIN_PATH" ]] || fatal "No neovim binary file found"

  [[ -n "$RUN_ALL_TEST" ]] && all_test

  [[ -n "$RUN_LIST" ]] && list

  single_test "$*"
}

main "$@"
